sudo: false
language: cpp
compiler:
    - gcc
    - clang

addons:
    # Install test environment for the client
    apt:
        sources:
            - deadsnake
        packages:
            - python3.4
            - python3.4-dev
            - python-virtualenv


before_install:
    # Install cpputest
    - pushd ..
    - wget "https://github.com/cpputest/cpputest.github.io/blob/master/releases/cpputest-3.6.tar.gz?raw=true" -O cpputest.tar.gz
    - tar -xzf cpputest.tar.gz
    - cd cpputest-3.6/
    - ./configure --prefix=$HOME/cpputest
    - make
    - make install
    - popd

    # Clone needed python dependencies
    - git clone https://github.com/cvra/serial-can-bridge.git



before_script:
    # packager requirements

    # Create client test environment
    - virtualenv --python=python3.4 venv
    - source venv/bin/activate
    - python --version
    - pip install -r client/requirements.txt
    - pip install -r packager/requirements.txt

    - pushd serial-can-bridge/python
    - python setup.py install
    - popd

    # Prepare bootloader build
    - ./packager/packager.py
    - mkdir build/
    - pushd build/
    - ls $HOME/cpputest
    - CMAKE_INCLUDE_PATH=$HOME/cpputest/include CMAKE_LIBRARY_PATH=$HOME/cpputest/lib cmake ..
    - deactivate
    - popd

script:
    # Booloader tests
    - pushd build/
    - make
    - ./tests
    - popd

    # Client tests
    - source venv/bin/activate
    - pushd client/
    - python -m unittest2
    - deactivate
    - popd

